In [0]:
x = [180, 170, 170, 175, 181, 175, 177, 185, 179, 160]
y = [95, 70, 60, 79, 60, 63, 83, 80, 75, 50]

In [0]:
x, len(x)

([180, 170, 170, 175, 181, 175, 177, 185, 179, 160], 10)

In [0]:
y, len(y)

([95, 70, 60, 79, 60, 63, 83, 80, 75, 50], 10)

In [0]:
import numpy as np

In [0]:
X = np.stack((x, y), axis = 0)
X

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [ 95,  70,  60,  79,  60,  63,  83,  80,  75,  50]])

In [0]:
sigma_1 = np.cov(X)
sigma_1

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

In [0]:
X_test= np.stack((x, x), axis = 0)
X_test

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [180, 170, 170, 175, 181, 175, 177, 185, 179, 160]])

In [0]:
sigma_2 = np.cov(X_test)
sigma_2

array([[50.62222222, 50.62222222],
       [50.62222222, 50.62222222]])

In [0]:
def generate_data():
  x = [180, 170, 170, 175, 181, 175, 177, 185, 179, 160]
  y = [95, 70, 60, 79, 60, 63, 83, 80, 75, 50]
  X = np.stack((x, y), axis = 0)
  return X

def get_cov_matrix(X):
  sigma_1 = np.cov(X)
  return sigma_1

In [0]:
data_1 = generate_data()
get_cov_matrix(data_1)

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

[Multivariate Normal](https://peterroelants.github.io/posts/multivariate-normal-primer/)

In [0]:
def multivariate_normal(x, d, mean, covariance):
    """pdf of the multivariate normal distribution."""
    x_m = x - mean
    return (1. / (np.sqrt((2 * np.pi)**d * np.linalg.det(covariance))) * 
            np.exp(-(np.linalg.solve(covariance, x_m).T.dot(x_m)) / 2))

In [0]:
x = generate_data()
np.mean(x[0, :]), np.mean(x[1, :])

(175.2, 71.5)

In [0]:
x_1 = [175, 72]
d_1 = 2

data = generate_data()
mean_1 = np.array([np.mean(x[0, :]), np.mean(x[1, :])])
covariance_1 = get_cov_matrix(data)

In [0]:
multivariate_normal(x_1, d_1, mean_1, covariance_1)

0.002178581612789265

In [68]:
for i in range(20):
  v = 160 + i
  x_1 = [v, 72]
  s = multivariate_normal(x_1, d_1, mean_1, covariance_1)
  print(v, " ", s)

160   3.900829561409074e-05
161   6.474366439009428e-05
162   0.0001038583704652072
163   0.0001610236472719428
164   0.00024129134356410786
165   0.0003494602240504497
166   0.000489167604054411
167   0.0006617920579089793
168   0.0008653451053442351
169   0.0010936064403862028
170   0.001335785435578412
171   0.0015769440170517839
172   0.0017992842345717487
173   0.001984208019848439
174   0.002114845053089614
175   0.002178581612789265
176   0.002169067369696109
177   0.0020872581976861993
178   0.0019412579031221177
179   0.0017449951542558313
